[198] Web create edit freak modal
Agilefreaks/FreaksCatalog-Web pull request #10
Opened 2021-08-25 13:10 UTC by MarianBadea

This PR will create the edit freak modal

2021-08-25 13:13 UTC, MarianBadea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Web: Create Edit Freak Modal](https://trello.com/c/rrDd10sD/198-web-create-edit-freak-modal)

2021-09-02 06:42 UTC, adrianbunea requested changes
Just one comment for this

2021-09-02 13:18 UTC, adrianbunea approved these changes

2021-09-02 13:21 UTC, luism-s requested changes

2021-09-06 13:31 UTC, adrianbunea requested changes

2021-09-06 13:31 UTC, adrianbunea commented on src/App.js
> +              <p>Projects</p>
BEM - Block, Element, Modifier, explain how "agile" is an `element` of the "app" `block`.

2021-09-06 13:31 UTC, adrianbunea commented on src/components/ConfirmDeleteModal/ConfirmDeleteModal.jsx
> +        <p>Are you sure you want to delete this freak?</p>
@MarianBadea bump

2021-09-07 07:58 UTC, merged