[147] Web graphql integrate app with api
Agilefreaks/FreaksCatalog-Web pull request #12
Opened 2021-09-02 08:51 UTC by MarianBadea

This PR will set up the integration with the API

2021-09-02 09:07 UTC, MarianBadea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Web: [graphql] Integrate app with API](https://trello.com/c/H7XvRbGz/147-web-graphql-integrate-app-with-api)

2021-09-14 12:10 UTC, luism-s requested changes

2021-09-29 11:12 UTC, adrianbunea commented on src/pages/ViewFreaks/ViewFreaks.jsx
> +          setOpenModal={ setOpenModal }
`onToggleModal` doesn't really fit though. I think the original mistake is including the trigger button for opening the modal as well, it hands over the responsibility of opening and closing the modal to the Modal itself, it should know how to close itself, but it definitely shouldn't know how to open itself as well. I will leave this as is for now, and we can look for a different approach someday.

2022-09-08 08:22 UTC, dasilvaluis approved these changes

2022-09-08 08:22 UTC, merged