[212] Web create home page
Agilefreaks/FreaksCatalog-Web pull request #13
Opened 2021-09-04 10:27 UTC by MarianBadea

This PR will create a home page for the app

2021-09-06 11:04 UTC, MarianBadea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Web: Create Home Page](https://trello.com/c/wRUB7i0I/212-web-create-home-page)

2021-09-08 11:53 UTC, luism-s requested changes

2021-09-08 11:53 UTC, luism-s commented on src/pages/Home/Home.scss
> +  h1 {
You shouldn't give style to native elements, instead give classes to the elements

2021-09-08 12:58 UTC, luism-s approved these changes
Very nicely done :)

2021-09-09 08:32 UTC, merged